= Matt Raible's IntelliJ IDEA Live Templates

These are the https://www.jetbrains.com/help/idea/using-live-templates.html[IntelliJ IDEA Live Templates] that I've used in many demos and screencasts over the years.

I tried using IntelliJ's https://www.jetbrains.com/help/idea/sharing-live-templates.html[sharing live templates], but failed to make it work.

https://www.jetbrains.com/idea/download/[Download IntelliJ IDEA] today! It's a spectacular IDEA for Java, Kotlin, TypeScript, JavaScript, S/CSS, and HTML.

If you clone this project and open it in IntelliJ (with the Asciidoctor plugin installed), you should be able to edit this file and add the shortcuts below as live templates.

== Spring Boot

**boot-entity**
[source,java]
----

----

**boot-h2**
[source,xml]
----

----

**boot-sql**
[source,sql]
----

----

**boot-repository**
[source,java]
----

----

**boot-command**
[source,java]
----

----

**boot-add**
[source,java]
----

----

**boot-controller**
[source,java]
----

----

**boot-good**
[source,java]
----

----

**okta-maven-boot**
[source,xml]
----

----

**spring-oauth2**
[source,yaml]
----

----

**okta-oauth2**
[source,yaml]
----

----

**cors-filter**
[source,java]
----

----

== Angular

**ng-giphy-service**
[source,typescript]
----

----

**ng-giphy-foreach**
[source,typescript]
----

----

**ng-okta-service**
[source,typescript]
----

----

**ng-okta-headers**
[source,ts]
----

----

**ng-okta-oninit**
[source,ts]
----

----

**ng-okta-login**
[source,ts]
----

----

**ng-okta-css**
[source,css]
----

----

== Cloud Foundry

**cf-manifest**
[source,yaml]
----

----

**cf-build**
[source,yaml]
----

----

**cf-react**
[source,bash]
----

----

== Heroku

**heroku-react**
[source,bash]
----

----

== JHipster

**jh-findBy**
[source,java]
----

----

**jh-date**
[source,ts]
----

----

**jh-entries**
[source,html]
----

----

== React

**okta-react-config**
[source,ts]
----

----

**okta-react-render**
[source,ts]
----

----

**okta-react-home**
[source,ts]
----

----

**okta-react-token**
[source,ts]
----

----

== Contributing

Want to add more of have you figured out how to import live templates? Send a pull request!
